### PR TITLE
bump wiremock to 0.6

### PR DESCRIPTION
**Pull request by brhoades**
:wave: I'm not sure if the maintainer is still around. But we use this crate at my company for testing. 

Unfortunately, this crate doesn't fully work with wiremock 0.6.

Cargo is happy to have the current version in the same crate with the latest wiremock. However, it breaks down in use. Here's an example failure where the parts matcher no longer satisfies the `Match` trait in new wiremock:

```
error[E0277]: the trait bound `wiremock_multipart::matchers::NumberOfParts: wiremock::Match` is not satisfied
   --> crates/clients/src/http.rs:450:18
    |
450 |             .and(NumberOfParts(2))
    |              --- ^^^^^^^^^^^^^^^^ the trait `for<'a> Fn(&'a wiremock::Request)` is not implemented for `wiremock_multipart::matchers::NumberOfParts`, which is required by `wiremock_multipart::matchers::NumberOfParts: wiremock::Match`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the following other types implement trait `wiremock::Match`:
              AnyMatcher
              BasicAuthMatcher
              BearerTokenMatcher
              BodyContainsMatcher
              BodyExactMatcher
              BodyPartialJsonMatcher
              HeaderExactMatcher
              HeaderExistsMatcher
            and 8 others
```

In this PR, I bumped the version and fixed APIs broken by wiremock-multipart 0.6.

I'd love to get this crate updated over using my fork. Please let me know what I can do to help!

### CODE REVIEW

**Comment by Leopard2A5** [comment]
Hi Billy!
Thanks for the pull request! I just merged it and published wiremock-multipart@1.0.0 😄

**Comment by brhoades** [comment]
Thank you for the quick turnaround!
